var LT = {
	"pipedrive_integration":		"Интеграция с pipedrive",
	"need_key_for_pipedrive":		"Необходимо ввести API ключ pipedrive",
	"invalid_api_key":				"Невалидный API ключ",
	"inner_error":					"Внутренняя ошибка",
	"incorrect_landing_id":			"Некорректный ID лендинга",
	"incorrect_landing_url":		"Некорректный URL лендинга",
	"incorrect_login_or_password":	"Некорректный логин или пароль",
	"incorrect_login":				"Некорректный логин",
	"incorrect_password":			"Неправильный пароль",
	"need_login_and_password":		"Необходимо ввести корректные логин и пароль",
	"integration_connected":		"Интеграция подключена",
	"integration_disconnected":		"Интеграция отключена",
	"group_saved":					"Группа сохранена",
	"template_saved":				"Шаблон сохранён",
	"incorrect_email":				"Некорректный e-mail",
	"incorrect_client_id":			"Некорректный идентификатор клиента",
	"incorrect_client_id_or_key":	"Неверные идентификатор или ключ",
	"incorrect_secret_key":			"Неправильный секретный ключ",
	"need_client_id_and_key":		"Необходимо ввести корректные идентификатор и ключ",
	"incorrect_api_key":			"Некорректный API-ключ",
	"missing_distribution_group":	"Отсутствует группа рассылки",
	"need_correct_api_key":			"Необходимо ввести корректный API-ключ",
	"invalid_login_or_password":	"Неверные логин или пароль",
	"need_url":						"Вы должны указать адрес для этой страницы",
	"error":						"Ошибка",
	"success_operation":			"Успешная операция",
	"invalid_value_of_notice_type":	"Недупустимое значение типа оповещения",
	"page_id_field_empty":			"Не заполнен ID страницы",

	"data_saved":					"Данные сохранены",
	"refresh_page_for_save":		"Обновите страницу, чтобы изменения вступили в силу",
	"cancel":						"Отменить",
	"delete_variant":				"Удалить вариант",
	"you_sure_for_remove":			"Вы уверены, что хотите удалить этот вариант?",
	"preview":						"Просмотр",
	"map_of_links":					"Карта ссылок",
	"you_sure_for_remove_stats_for_page":		"Вы уверены, что хотите удалить всю статистику для этой страницы?",
	"you_sure_for_remove_stats_for_variant":	"Вы уверены, что хотите удалить всю статистику для этого варианта?",

	"delete_page":					"Удалить страницу",
	"yes_delete_now":				"Да, удалить сейчас!",
	"upgrade_tariff":				"Перейти на новый тариф",
	"why_it_necessary":				"Зачем это нужно?",
	"add_new_source":				"Добавить новый источник",
	"read_more":					"Подробнее",
	"invalid_format_of_link":		"Неправильный формат ссылки!",
	"about_integration":			"Об интеграции",
	"setting_of_answering_machine":	"Настройка автоответчика",
	"disable_integration":			"Отключить интеграцию",
	"add":							"Добавить",
	"close":						"Закрыть",
	"save":							"Сохранить",
	"enable_integration":			"Включить интеграцию",
	"remove_stats":					"Подождите. Идет обнуление статистики",

	"group_success_created": "Группа успешно создана",
	"groups_for_page_success_refresh": "Группы для этой страницы успешно обновлены",
	"group_success_edited": "Группа успешно отредактирована",
	"remove_group": "Удалить группу",
	"ask_remove_group_permanently": "Удалить эту группу навсегда?",
	"group_success_deleted": "Группа успешно удалена",
	"wait_a_bit": "Подождите немного",
	"Search": "Поиск",

	"invalid_data_entered_css_cleared": "Внимание, вы пытаетесь ввести неверные данные. Чистый CSS был очищен",
	"cant_refresh_category": "Не получается обновить категорию",
	"cant_create_category": "Не получается создать категорию",
	"cant_remove_category": "Не получается удалить категорию",
	"cant_rename_category": "Не получается переименовать категорию",
	"cant_move_image": "Не удалось переместить картинку",
	"cant_move_images": "Не удалось переместить картинки",
	"cant_remove_image": "Не удалось удалить картинку",
	"cant_remove_images": "Не удалось удалить картинки",
	"cant_save_image": "Не удалось сохранить изображение",
	"attention_error_of_loading_save_disabled": "Внимание, при загрузке редактора произошла ошибка. Сохранение страницы отключено. Попробуйте перезагрузить страницу. Если ошибка будет повторяться, обратитесь в службу поддержки:",
	"old_browser": "Вы используете устаревшую версию браузера. Роботоспособность сервиса не гарантируется",
	"page_have_unsaved_data": "На странице остались несохраненные изменения. Действительно хотите выйти?",
	"remove_from_history": "Удаляем с хистори",
	"remove_all_elements_from_section": "Удалить все элементы секции",
	"remove_element": "Удалить элемент",
	"yes_remove_now": "Да, удалить сейчас!",
	"save_section": "Сохранить секцию",
	"section_and_n_block": "Секция и %@ блоков",
	"name_required": "Заполните название",
	"select_category": "Выберите категорию",
	"select_preview": "Выберите превью",
	"select_little_preview": "Выберите маленькое превью",
	"invalid_format_of_preview": "Не правильный формат превью",
	"invalid_format_of_little_preview": "Не правильный формат маленького превью",
	"section_success_saved": "Секция успешно сохранена",
	"error_saved_section": "Ошибка при сохранении секции. Обратитесь в службу технической поддержки",
	"header": "Шапка",
	"benefits": "Выгоды",
	"work_stages": "Этапы работы",
	"gallery": "Галерея",
	"lead_form": "Лид-форма",
	"feedback": "Отзывы",
	"footer": "Футер",
	"typeless": "Без типа",
	"services": "Услуги",
	"my_section": "Мои секции",
	"error_during_loading_data": "Ошибка во время загрузки данных",
	"need_help": "Нужна помощь?",
	"constructor_of_section": "Конструктор секций",
	"send": "Отправить",
	"welcome_to_editor": "Добро пожаловать в визуальный редактор!",
	"control_panel": "Панель инструментов",
	"select_here_tools_for_landings": "Здесь вы можете выбрать основные инструменты для редактирования вашего лендинга",
	"elements_of_page": "Элементы страницы",
	"widget_collection_for_landings": "Коллекция виджетов LPgenerator, предназначена для удобной графической и функциональной настройки вашего лендинга",
	"widget_panel": "Панель виджетов",
	"all_elements_here_click_for_selection": "Здесь перечислены все элементы лендинга. Кликните по элементу для его выделения в визуальном редакторе",
	"properties_panel_of_elements": "Панель свойств элементов",
	"enter_properties_here_for_elements": "Здесь вы можете задать основные свойства выбранного элемента целевой страницы: размеры, цвет, фон и т.д.",
	"switcher_panel": "Панель переключения",
	"use_this_for_switch_between_variants": "Используйте этот функционал для создания или переключения визуального редактора между вариантами лендинга (применяется при настройке сплит-теста)",
	"video_lessons": "Видео-уроки",
	"video_tooltip": "Видео-подсказка",
	"without_category": "Без категории",
	"choose_image": "Выберите изображение",
	"select": "Выбрать",
	"cant_delete_image_used": "Одно или несколько из выбранных изображений используется, не могу удалить.",
	"confirm_delete": "Действительно удалить?",
	"error_uploading_image": "Ошибка при загрузке изображения",
	"image_required": "Выберите картинку!",
	"block": "Блок",
	"button": "Кнопка",
	"add_button": "Добавить кнопку",
	"in_current_window": "В том же окне",
	"in_new_window": "В новом окне",
	"additional_fonts": "Дополнительные шрифты",
	"detailed_guide": "Подробное руководство",
	"add_form": "Добавить форму",
	"fields_in_form_required": "Необходимо добавить в форму хотя бы одно поле",
	"payment_setting_required": "Необходимо заполнить настройки оплаты",
	"add_gallery": "Добавить Галерею",
	"solid": "Сплошная",
	"dashed": "Пунктирная",
	"dotted": "Точечная",
	"goals_for_conversion": "Цели конверсии",
	"add_html": "Добавить html",
	"image": "Изображение",
	"zoom_settings": "Настройки приближения",
	"no_style": "Без стиля",
	"big_chars": "Большие буквы",
	"little_chars": "Маленькие буквы",
	"first_char_is_big": "Первая большая",
	"dynamic_variables": "Динамические переменные",
	"map": "Карта",
	"add_map": "Добавить карту",
	"yandex_map": "Яндекс.Карты",
	"meta_tags": "Meta теги",
	"add_meta_tags": "Добавить meta теги",
	"page": "Страница",
	"form": "форма",
	"text_of_text": "Текстовый текст",
	"popup": "Попап",
	"request_call": "Заказать звонок",
	"thanks_for_info": "Спасибо за информацию!",
	"alert_deny_with_form_break": "Недоступно при наличии разрыва страницы",
	"alert_deny_with_horizontal_murkup": "Недоступно для горизонтальной разметки",
	"alert_deny_two_columns": "Недоступно для 2 колонок",
	"name": "Имя",
	"phone": "Телефон",
	"add_popup": "Добавить попап",
	"enter_count_of_seconds": "Введите корректное количество секунд",
	"enter_count_of_pixels": "Введите корректное количество пикселей",
	"markup_and_styles": "Разметка и стили",
	"appearances": "Варианты появления",
	"by_timer": "По таймеру",
	"by_scroll": "По прокрутке",
	"when_try_close_page": "При попытке закрыть страницу",
	"leave_from_above": "Выезжать сверху",
	"leave_from_below": "Leave from below",
	"leave_from_left": "Выезжать слева",
	"leave_from_right": "Выезжать справа",
	"slow_appearance_center": "Медленное появление по центру",
	"widget_popup_showActions_prompt": "Выберите событие",
	"widget_popup_showActions_click": "Показывать по клику",
	"widget_popup_animationTypes_prompt": "Выберите тип анимации",
	"show": "Показывать",
	"privacy_give_agree": "Я согласен на обработку своих персональных данных",
	"privacy_give_agree_chb_value": "Согласен на обработку данных",
	"skip_training_and_close": "Пропустить обучение и закрыть",
	"images_already_in_category": "Картинки уже находятся в данной категории",
	"field_link_is_empty": "В поле 'ссылка' необходимо указать валидный url страницы",
	"big_text": "Большой текст",
	"enter_text": "Введите текст",
	"field": "Поле",
	"enter_name": "Введите название",
	"popup_settings": "Настройки попапа",
	"send_button": "Кнопка отправить",
	"CALL_ME": "ПОЗВОНИТЕ МНЕ",
	"text": "Текст",
	"double_click_for_rename": "Двойной клик для переименования",
	"simple": "Простые",
	"extended": "Расширенные",
	"multiline_field": "Многострочное Поле",
	"up_left": "Верх слева",
	"up_center": "Верх центр",
	"up_right": "Верх справа",
	"center_left": "Центр слева",
	"center": "Центр",
	"center_right": "Центр справа",
	"down_left": "Низ слева",
	"down_center": "Низ центр",
	"down_right": "Низ справа",
	"no_repeat": "Без повторения",
	"horizontal": "Горизонтальное",
	"vertical": "Вертикальное",
	"propagate": "Размножить",
	"general": "Общее",
	"surname": "Фамилия",
	"left": "Слева",
	"right": "Справа",
	"by_center": "По центру",
	"robokassa": "Робокасса",
	"pay!": "Оплатить!",
	"field_login_is_empty": "Поле 'логин' не заполнено",
	"invalid_chars_in_login_field": "Вы ввели недопустимые символы в поле 'логин'",
	"field_description_is_empty": "Поле 'описание' не заполнено",
	"field_password_is_empty": "Поле 'пароль' не заполнено",
	"invalid_chars_in_password_field": "Вы ввели недопустимые символы в поле 'пароль'",
	"field_password2_is_empty": "Поле 'пароль 2' не заполнено",
	"invalid_chars_in_password2_field": "Вы ввели недопустимые символы в поле 'пароль 2'",
	"field_button_text_is_empty": "Поле 'текст кнопки' не заполнено",
	"new_script": "Новый скрипт",
	"add_scripts": "Добавить скрипты",
	"into_tag": "Внутри тега",
	"after_tag": "После тега",
	"before_tag": "Перед тегом",
	"section": "Секция",
	"slider": "Слайдер",
	"add_slider": "Добавить Слайдер",
	"add_text": "Добавить текст",
	"timer": "Таймер",
	"days": "дней",
	"hours": "часов",
	"minutes": "минут",
	"seconds": "секунд",
	"add_timer": "Добавить таймер",
	"date_required": "Укажите дату",
	"timer_scale_not_available_after_save": "Масштаб таймера и другие настройки доступны в редакторе после сохранения",
	"video": "Видео",
	"add_video": "Добавить видео",
	"field_amount_is_empty": "Поле 'сумма' не заполнено",
	"about_constructor_form": "О работе с конструктором форм",
	"need_complete_editing_element": "Необходимо завершить редактирование элемента.",
	"you_not_add_fields": "'Вы не добавили к форме полей",
	"saving_error": "Ошибка сохранения",
	"unknown_error": "неизвестная ошибка",
	"call_to_support": "Обратитесь в службу поддержки.",
	"additional_setting_allow_after_save": "Расширенные настройки кнопки вызова Попап доступны в редакторе после сохранения",
	"link": "ссылка",
	"Link": "Ссылка",
	"transparent": "прозрачный",
	"clear": "очистить",
	"field_must_be_entered": "Поле %@ должно быть заполнено",
	"enter_this_field": "Заполните это поле",
	"error_sending_data_try_latter": "Ошибка отправки данных. Попробуйте отправить запрос попозже.",
	"enter_valid_email": "Введите правильный email",
	"second_send_deny": "Повторная отправка одинаковых данных невозможна/запрещена",

	/*Андбординг*/
	"next": "Далее",
	"Welcome": "Добро пожаловать!",
	'editor_have_many_functions': "Визуальный редактор содержит огромный функционал.<br>Вы можете конструировать лендинги любой сложности &mdash; с нуля или используя более 500 шаблонов нашей галереи.",
	"fast_learn__how_create_page": "Приступим к быстрому обучению.<br>Сделайте вашу посадочную страницу всего за 3 минуты.",
	"next2": "Вперед",
	"skip_tutorial": "Пропустить обучение",
	"section_constructor": "Конструктор секций",
	"press_icon_for_section_constructor": "Нажмите на иконку, чтобы открыть виджет «Конструктор секций» и создать лендинг из готовых графических блоков",
	"Head": "Шапка",
	"Select_header_for_landing": "Выберите шапку (первый экран) для вашего лендинга",
	"next_step": "Следующий шаг",
	"add_next_block": "Отлично, теперь добавьте следующий графический блок",
	"block_benefits": "Блок “Выгоды”",
	"press_for_select": "Нажмите чтобы выбрать",
	"left_some_steps": "Осталось несколько шагов",
	"set_contact_form_for_landing": "Поставьте контактную форму на свою посадочную страницу",
	"lead_form_is_form": "“Лид-форма” - форма сбора заявок",
	"Final_block": "Заключительный блок",
	"Half_landing_without": "Ваш лендинг будет неполным без подвала или футера",
	"Footer": "Футер",
	"Block_footer": "Блок “Футер“",
	"Congratulation": "Поздравляем!",
	"First_landing_ready": "Ваш первый лендинг готов, нажмите кнопку “Сохранить” изменения",
	"Move_to_preview": "Переходим к просмотру",
	"lets_preview_landing": "Давайте посмотрим как выглядит ваш лендинг. Нажмите на кнопку “Просмотр” (откроется новая вкладка браузера), а затем вернитесь в редактор.",
	"Return_to_edit_landing": "Вернитесь в редактор лендинга,<br>чтобы завершить настройку и публикацию вашей посадочной страницы",
	"Return_to_editor": "Вернуться в редактор",
	"Here_select_main_instruments": "Здесь вы можете выбрать основные инструменты для редактирования вашего лендинга",
	"Elements_of_page": "Элементы страницы",
	"Here_all_elements": "Здесь перечислены все элементы лендинга. Кликните по элементу для его выделения в визуальном редакторе.",
	"Widget_panel": "Панель виджетов",
	"Widget_collection_for_landing": "Коллекция виджетов LPgenerator предназначена для удобной графической и функциональной настройки вашего лендинга",
	"Properties_panel": "Панель свойств элементов",
	"Here_main_props_of_page": "Здесь вы можете задать основные свойства выбранного элемента целевой страницы: размеры, цвет, фон и т.д.",
	"Video_help": "Видео-подсказки",
	"Video_help_highlight_for_use_tools": "Вам подсвечиваются видео-подсказки, с их помощью вы быстро научитесь пользоваться каждым инструментом редактора",
	"Success_complete_tutorial_with_editor": "Вы успешно прошли базовое знакомство с редактором LPgenerator. Все нужные изменения и настройки вы сможете сделать позже самостоятельно. Давайте опубликуем ваш лендинг в интернете.",
	"Publish_landing_per_click": "Опубликуйте ваш тестовый лендинг в один клик",
	"Press_button_for_publish": "Нажмите на кнопку и лендинг появится в Интернете",
	"How_your_name": "Как вас зовут?",
	"Add_password": "Задайте пароль",
	"What_need_solve_problem": "Какую задачу вы хотите решить с помощью платформы",
	"Enter_your_name_for_tools": "Представьтесь, чтобы мы смогли предоставить вам персонализированные инструменты и сервис",
	"Need_enter_name": "Необходимо указать имя",
	"Need_enter_password": "Необходимо задать пароль",
	"Need_enter_phone": "Необходимо указать телефон",
	"What_you_want_from_platform": "Укажите какую задачу хотели бы решить",
	"Select_if_have_site": "Поставьте галочку если у вас есть сайт или лендинг",
	"I_have_site": "У меня есть сайт или лендинг",
	"Subscribe_to_blog": "Подписаться на блог",
	"Enter_your_answer": "Введите ответ на вопрос",
	"Enter_your_answer_variant": "Введите ваш вариант ответа",
	"Your_answer": "Ваш ответ",
	"Other": "Другое",
	"Your_phone": "Ваш телефон",
	"What_your_position": "Какую должность занимаете?",
	"What_your_niche": "Какая у вас ниша?",
	"mmStep_01_select_wq_placeholder": "Сколько человек работает в компании?",
	"mmStep_01_select_wq_isEmpty": "Не указанно количество сотрудников",
	"blogHintTxt0": "Получайте ежедневную подборку свежих статей из нашего блога об интернет-маркетинге.",
	"blogHintTxt1": "Повышайте эффективность лендингов, изучайте примеры реальных кейсов, рабочие стратегии и лайфхаки привлечения клиентов.",
	"blogHintTxt2": "Присоединяйтесь к 32000 подписчикам.",
	"tutorial_segmentation_title": "Вы работали с конструкторами лендингов/сайтов?",
	"tutorial_segmentation_l1": "Как часто работали с конструкторами сайтов?",
	"tutorial_segmentation_select_t0": "Не работал или работал(а) 1-2 раза",
	"tutorial_segmentation_select_t1": "Знаком с одним или более конструкторами",
	"tutorial_segmentation_select_t2": "Другое",
	"tutorial_segmentation_plh1": "Введите ваш вариант",
	"tutorial_welcome_title": "Добро пожаловать в LPgenerator!",
	"tutorial_welcome_text1": "Используйте любой из 500 шаблонов посадочных страниц нашей галереи, чтобы создать лендинг на его основе.",
	"tutorial_welcome_text2": "Или переходите прямо в визуальный редактор, чтобы создать лендинг с нуля с помощью конструктора секций с готовыми блоками или при помощи других инструментов.",
	"tutorial_welcome_nextBtn": "Перейти в редактор",
	"tutorial_welcome_toGalleryBtn": "Перейти в галерею",
	"tutorial_end_text0": "Вы прошли базовое обучение и можете приступать к созданию лендинга для вашего бизнеса.",
	"tutorial_end_text1": "Чтобы создать посадочную страницу с нуля, выберите пустой шаблон или используйте один из 500 макетов в галерее LPgenerator.",
	"tutorial_end_text2": "Короткая видео-инструкция поможет вам быстро изучить весь функционал.",
	"tutorial_end_btn0": "Лендинг с пустого шаблона",
	"tutorial_end_btn1": "Выбрать шаблон в галерее",

	"closePP_txt0": "Выходим из обучения.",
	"closePP_txt1": "Хотите продолжить работу над этой страницей без обучения или начать на новой без элементов?",
	"closePP_bnt0": "Продолжить на этой",
	"closePP_bnt1": "Начать на новой",
	"closePP_bnt2": "Отмена",

	"new_page": "Новая страница",
	"first_variant": "Первый вариант",

	"vat_label": "Ставка НДС",
	"vat_prompt": "Выберите ставку НДС",
	"vat_none": "Без НДС",
	"vat_vat0": "НДС по ставке 0%",
	"vat_vat10": "НДС чека по ставке 10%",
	"vat_vat18": "НДС чека по ставке 18%",
	"vat_vat110": "НДС чека по расчетной ставке 10/110",
	"vat_vat118": "НДС чека по расчетной ставке 18/118",
	"vat_field_empty": "Необходимо выбрать НДС",

	"free_style": "Произвольный стиль",

	"language": "язык",
	"lang_prompt_section": "Выберите язык секции",
	"lang_verification_0": "Необходимо выбрать язык",
	"lang_en": "Английский",
	"lang_pl": "Польский",
	"lang_ru": "Русский",

	"choose_category": "Выберите категорию",
	"choose_subcategory": "Выберите подкатегорию",
	"overlayText": "Кликните для добавления секции",
	"incorrect_url": "Некорректный url",

	"dynamic_text": "Динамический текст",
	"lineheight_plugin_text0": "Высота строки",
	"lineheight_plugin_text1": "Укажите желаемую высоту строки (за единицу принят размер шрифта, 1em).",
	"editor_background_plugin_text0": "Цвет фона редактора",

	"success_pay_default_msg": "Спасибо! Платеж успешно совершен.",
	"fail_pay_default_msg": "Ошибка платежа!",
	"Payment_connect": "Подключение оплаты",
	"Add_payment_type": "Добавление способа оплаты",
	"payment":	"оплата",
	"Payment":	"Оплата",
	"zapier_integration": "Интеграция с Zapier",

	"expecto_integration": "Интеграция с Expecto.me",

	"webhook_integration": "Интеграция webhooks",
	"webhook_integration_add": "Добавить webhook",
	"webhook_integration_edit": "Редактирование webhook",
	"Payment_list":	"Способы оплаты",
	"payment_form_email_required": "По требованиям Яндекс Кассы, при использовании НДС, необходимо обазятельно отправлять email покупателя. Для успешного совершения посетителями оплат, необходимо в форму добавить поле Email",
	"payment_email_required_deny": "По требованиям Яндекс Кассы, при использовании НДС, необходимо обазятельно отправлять email покупателя. Используйте инструмент для создания формы, чтобы добавить поле email и настроить прием платежей с помощью яндекса.",
	"Payment_settings_required": "Необходимо указать настройки оплаты",
	"Revisions_history": "История версий",
	"Google_font_connect": "Подключение google шрифтов",
	"blockOverflow": "Данный блок выходит за пределы страницы",
	"Animations_select": "Выбор анимации"
};
